# https://github.com/apache/infrastructure-asfyaml/blob/main/README.md
---
github:
  description: "Web site for Apache Data Privacy"
  homepage: https://privacy.apache.org/
  labels:
    - apache
    - privacy
    - website
    - jekyll
jekyll:
  whoami: main
  target: asf-site
publish:
  whoami: asf-site
notifications:
  commits: privacy-commits@apache.org
  issues:  privacy-commits@apache.org
  pullrequests: privacy-commits@apache.org

